In [240]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import random


In [241]:
df=pd.read_csv("Loan_approval_clean.csv",index_col=0)
df.head()

Loan_ID  Gender  Married  Dependents  Education  Self_Employed  \
0  LP001002       1        0           0          1              1   
1  LP001003       1        1           1          1              1   
2  LP001005       1        1           0          1              1   
3  LP001006       1        1           0          0              1   
4  LP001008       1        0           0          1              1   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0           467920                0.0     10240.0             360.0   
1           366640           120640.0     10240.0             360.0   
2           240000                0.0      5280.0             360.0   
3           206640           188640.0      9600.0             360.0   
4           480000                0.0     11280.0             360.0   

   Property_Area  Loan_approved  Credit_Score  
0              0              1           799  
1              1              0           727  
2              0              1           782  
3              0              1           722  
4              0              1           715

In [242]:
df.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Property_Area        0
Loan_approved        0
Credit_Score         0
dtype: int64

In [243]:
df.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Property_Area', 'Loan_approved', 'Credit_Score'],
      dtype='object')

In [244]:
X=df.drop(columns=['Loan_approved','Loan_ID'],axis=1)
Y=df['Loan_approved']

In [245]:
Y

0      1
1      0
2      1
3      1
4      1
      ..
609    1
610    1
611    1
612    1
613    0
Name: Loan_approved, Length: 614, dtype: int64

In [246]:
type(X)


pandas.core.frame.DataFrame

In [247]:
if X.shape[0] != Y.shape[0]:
  print("X and y rows are mismatched, check dataset again")
else:
  print("OK")

OK


In [248]:
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, mean_squared_error,accuracy_score
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression


X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, shuffle=True,random_state=0)
model = RandomForestClassifier(n_estimators=19,max_features=0.2,max_depth=6,max_samples=0.5)

model.fit(X_train, Y_train)


RandomForestClassifier(max_depth=6, max_features=0.2, max_samples=0.5,
                       n_estimators=19)

In [249]:
predictions=model.predict(X_test)

In [250]:
model.score(X_train,Y_train)

0.8152173913043478

In [251]:
model.score(X_test,Y_test)

0.7727272727272727

In [252]:
n_estimators = [20,40,60,80,100,120]

max_features = [0.2,0.6,0.8,1.0]

max_depth = [2,4,6,8,None]

max_samples = [0.25,0.5,0.75,1.0]



In [253]:
param_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
              'max_samples':max_samples
             }
print(param_grid)

{'n_estimators': [20, 40, 60, 80, 100, 120], 'max_features': [0.2, 0.6, 0.8, 1.0], 'max_depth': [2, 4, 6, 8, None], 'max_samples': [0.25, 0.5, 0.75, 1.0]}


In [254]:
rf = RandomForestClassifier()
from sklearn.model_selection import GridSearchCV

rf_grid = GridSearchCV(estimator = rf, 
                       param_grid = param_grid, 
                       cv = 5, 
                       verbose=2, 
                       n_jobs = -1)
rf_grid.fit(X_train,Y_train)


Fitting 5 folds for each of 480 candidates, totalling 2400 fits


GridSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'max_depth': [2, 4, 6, 8, None],
                         'max_features': [0.2, 0.6, 0.8, 1.0],
                         'max_samples': [0.25, 0.5, 0.75, 1.0],
                         'n_estimators': [20, 40, 60, 80, 100, 120]},
             verbose=2)

In [255]:
rf_grid.best_estimator_

RandomForestClassifier(max_depth=2, max_features=0.6, max_samples=0.75,
                       n_estimators=20)

In [256]:
rf_model=RandomForestClassifier(max_depth=2, max_features=0.6, max_samples=0.75)
rf_model.fit(X_train,Y_train)
rf_model.score(X_test,Y_test)

0.7792207792207793

max_depth=5, max_features=0.6, max_samples=0.5,
                       n_estimators=12
Best

In [260]:
prediction=rf_model.predict(X_test)
confusion_matrix(Y_test,prediction)

array([[ 19,  24],
       [ 10, 101]], dtype=int64)

In [261]:
X_test.iloc[0]

Gender                    1.0
Married                   0.0
Dependents                0.0
Education                 1.0
Self_Employed             1.0
ApplicantIncome      566800.0
CoapplicantIncome         0.0
LoanAmount             6720.0
Loan_Amount_Term        360.0
Property_Area             2.0
Credit_Score            757.0
Name: 454, dtype: float64

In [266]:
X_test.columns

Index(['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
       'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Property_Area', 'Credit_Score'],
      dtype='object')

In [263]:
len(X_test.columns)

11

In [276]:
list1=X_test.columns
l=[]
for i in range(0,len(X_test.columns)):
    print(f"Enter {list1[i]}")
    x=int(input())
    l.append(x)
print(l)



Enter Gender
Enter Married
Enter Dependents
Enter Education
Enter Self_Employed
Enter ApplicantIncome
Enter CoapplicantIncome
Enter LoanAmount
Enter Loan_Amount_Term
Enter Property_Area
Enter Credit_Score
[1, 0, 0, 1, 0, 400000, 0, 90000, 20, 0, 710]


In [277]:
custom_input=np.array(l).reshape(1,-1)
custom_input

array([[     1,      0,      0,      1,      0, 400000,      0,  90000,
            20,      0,    710]])

In [280]:
values=pd.DataFrame(custom_input,columns=X_test.columns)
values

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0       1        0           0          1              0           400000   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Property_Area  \
0                  0       90000                20              0   

   Credit_Score  
0           710

In [281]:
custom_input_prediction=model.predict(values)
custom_input_prediction

array([1], dtype=int64)

In [282]:
import pickle
pickle.dump(rf_model,open('model.pkl','wb'))

In [291]:
model=pickle.load(open('model.pkl','rb'))
model.predict(np.array(l).reshape(1,-1))


c:\Users\faize\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)